service:
  name: couchbase-serverless-backend

plugins:
  - serverless-dotenv-plugin

package:
  exclude:
    - "layers/**"
    - ".env*"
    - "**/*.secret"
    - ".gitsecret/**"
    - ".vscode/**"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  memorySize: 256

custom:
  couchbase-sdk-layer: !Join
    - ""
    - - "arn:aws:lambda:"
      - !Ref "AWS::Region"
      - ":"
      - !Ref "AWS::AccountId"
      - :layer:couchbase-node-sdk-2-6-11
      - :${env:COUCHBASE_NODE_SDK_LAYER_VERSION}

functions:
  create:
    handler: src/create.default
    layers:
      - ${self:custom.couchbase-sdk-layer}
    events:
      - http:
          method: post
          path: /

  read:
    handler: src/read.default
    layers:
      - ${self:custom.couchbase-sdk-layer}
    events:
      - http:
          method: get
          path: /{contactId}
          cors: true
          request:
            parameters:
              paths:
                contactId: true

  update:
    handler: src/update.default
    layers:
      - ${self:custom.couchbase-sdk-layer}
    events:
      - http:
          method: put
          path: /{contactId}
          cors: true
          request:
            parameters:
              paths:
                contactId: true

  delete:
    handler: src/delete.default
    events:
      - http:
          method: delete
          path: /{contactId}
          cors: true
          request:
            parameters:
              paths:
                contactId: true
