service:
  name: couchbase-serverless-backend

plugins:
  - serverless-dotenv-plugin

package:
  exclude:
    - "layers/**"
    - ".env*"
    - "**/*.secret"
    - ".gitsecret/**"
    - ".vscode/**"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  memorySize: 256

custom:
  couchbase-sdk-layer:
    Fn::ImportValue: couchbase-node-sdk-2-6-11-layer

functions:
  create:
    handler: src/create.default
    layers:
      - ${self:custom.couchbase-sdk-layer}
    events:
      - http:
          method: post
          path: /
          cors: true

  read:
    handler: src/read.default
    layers:
      - ${self:custom.couchbase-sdk-layer}
    events:
      - http:
          method: get
          path: /{contactId}
          cors: true
          request:
            parameters:
              paths:
                contactId: true

  update:
    handler: src/update.default
    layers:
      - ${self:custom.couchbase-sdk-layer}
    events:
      - http:
          method: put
          path: /{contactId}
          cors: true
          request:
            parameters:
              paths:
                contactId: true

  delete:
    handler: src/delete.default
    layers:
      - ${self:custom.couchbase-sdk-layer}
    events:
      - http:
          method: delete
          path: /{contactId}
          cors: true
          request:
            parameters:
              paths:
                contactId: true
